"""
plot_baseline.py — Reproduce the 4 top-K baseline figures from pre-computed data.

Requires ONLY the JSON files generated by basline.py:
    baseline_10k.json, baseline_20k.json, baseline_50k.json, baseline_100k.json

No raw domain names or rankings are needed.

Usage:
    python plot_baseline.py
    python plot_baseline.py --dir /path/to/jsons --outdir ./figs
"""

import json
import argparse
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.ticker import AutoMinorLocator
import matplotlib.transforms as transforms
from matplotlib.transforms import blended_transform_factory


def draw_topk_fig(data, out_pdf=None,
                  y_ticks=(-20,-10,-5,-2,-1,-0.5,-0.4,-0.3,-0.2,-0.1,
                            0,0.1,0.2,0.3,0.4,0.5,1,2,5,10,20),
                  y_linthresh=0.5):
    x_ratio = data["x_ratio"]
    top     = data["top"]
    sys_c,sys_lo,sys_hi = data["sys_c"],data["sys_lo"],data["sys_hi"]
    rnd_c,rnd_lo,rnd_hi = data["rnd_c"],data["rnd_lo"],data["rnd_hi"]
    sw  = data["swing_stats"]
    prm = data["params"]
    band=prm["band"]; band_mode=prm["band_mode"]; N_POP=prm["max_N"]

    fig, ax = plt.subplots(figsize=(8, 4.3))

    COLOR_TOP      = "#6b24bf"
    COLOR_SYS_BAND = "#FDB863"; COLOR_SYS_MED = "#E66101"
    COLOR_RND_BAND = "#A6CEE3"; COLOR_RND_MED = "#1F78B4"

    ax.plot(x_ratio, top, color=COLOR_TOP, lw=1.2, label="Top N", zorder=3)

    suffix = ("mean, " if band_mode=="meancenter" else "") + f"median, {int(band*100)}% interval"
    ax.fill_between(x_ratio, sys_lo, sys_hi,
                    color=COLOR_SYS_BAND, alpha=0.30, label=f"Systematic ({suffix})")
    ax.plot(x_ratio, sys_c, color=COLOR_SYS_MED, lw=1.2)
    ax.fill_between(x_ratio, rnd_lo, rnd_hi,
                    color=COLOR_RND_BAND, alpha=0.30, label=f"Random ({suffix})")
    ax.plot(x_ratio, rnd_c, color=COLOR_RND_MED, lw=1.2)
    ax.axhline(0, color="gray", linestyle="--", lw=1.0, alpha=0.8)

    ax.set_xlabel(f"Sample size as fraction of top {N_POP:,} websites", fontsize=14)
    ax.set_ylabel("Deviation from baseline (%)", fontsize=14, labelpad=1)
    ax.tick_params(axis="both", labelsize=13)
    ax.set_xlim(0.05, 1.0)
    ax.xaxis.set_major_locator(mticker.MaxNLocator(nbins=15))
    ax.xaxis.set_minor_locator(AutoMinorLocator(2))
    ax.set_ylim(-20.0, 20.0)
    ax.set_yscale("symlog", linthresh=y_linthresh, linscale=1.2, base=10)
    ax.set_yticks(list(y_ticks))
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.2f"))
    ax.yaxis.set_minor_locator(AutoMinorLocator(4))
    ax.grid(True, which="major", linestyle="--", alpha=0.55, linewidth=0.8)
    ax.grid(True, which="minor", linestyle=":",  alpha=0.25, linewidth=0.6)

    def _ann(label, st, CPEAK, CRMS, xp, xr):
        if st is None: return
        ax.axhline(st["peak_original"], color=CPEAK, linestyle="--", lw=1.6, alpha=0.8)
        ax.axhline(st["rms"],           color=CRMS,  linestyle="-.", lw=1.6, alpha=0.8)
        trans  = blended_transform_factory(ax.transAxes, ax.transData)
        offset = transforms.ScaledTranslation(0, 0.02, ax.figure.dpi_scale_trans)
        ax.text(xp, st["peak_original"], f"{label} |Peak|={st['peak_abs']:.2f}",
                fontsize=14, color=CPEAK, ha="left", va="bottom", transform=trans+offset)
        ax.text(xr, st["rms"],           f"{label} RMS={st['rms']:.2f}",
                fontsize=14, color=CRMS,  ha="left", va="bottom", transform=trans+offset)

    _ann("Top",        sw["top"],        "#5A1E9A","#3A3A3A", 0.02, 0.02)
    _ann("Systematic", sw["systematic"], "#D97A00","#A85E00", 0.25, 0.30)
    _ann("Random",     sw["random"],     "#125EAB","#156abf", 0.60, 0.65)

    ax.legend(frameon=True, fontsize=13, loc="lower right", framealpha=0.8)
    plt.tight_layout()
    if out_pdf:
        fig.savefig(out_pdf, dpi=300, bbox_inches="tight", pad_inches=0)
        print(f"  Saved → {out_pdf}")
    return fig, ax


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Reproduce 4 top-K baseline figures from pre-computed JSON data."
    )
    parser.add_argument("--dir",    default=".",
                        help="Directory containing the JSON files (default: .)")
    parser.add_argument("--outdir", default=".",
                        help="Directory to write output PDFs (default: .)")
    args = parser.parse_args()

    Y_TICKS = (-20,-10,-5,-2,-1,-0.5,-0.4,-0.3,-0.2,-0.1,
                0,0.1,0.2,0.3,0.4,0.5,1,2,5,10,20)

    FILES = [
        ("baseline_10k.json",  "10k.pdf"),
        ("baseline_20k.json",  "20k.pdf"),
        ("baseline_50k.json",  "50k.pdf"),
        ("baseline_100k.json", "100k.pdf"),
    ]

    for json_name, pdf_name in FILES:
        json_path = os.path.join(args.dir,    json_name)
        pdf_path  = os.path.join(args.outdir, pdf_name)

        if not os.path.exists(json_path):
            print(f"[SKIP] {json_path} not found.")
            continue

        print(f"Loading {json_path} …")
        with open(json_path) as f:
            data = json.load(f)

        prm = data.get("params", {})
        print(f"  max_N={prm.get('max_N')}  steps={len(data['x_ratio'])}"
              f"  seed={prm.get('seed')}")

        fig, ax = draw_topk_fig(data, out_pdf=pdf_path, y_ticks=Y_TICKS)
        plt.close(fig)

    print("\nDone.")
