"""
plot_hybrid.py — Reproduce the hybrid sampling figure from pre-computed data.

Requires ONLY: hybrid_data.json  (generated by hybrid.py)
No raw domain names or rankings are needed.

Usage:
    python plot_hybrid.py
    python plot_hybrid.py --data ./hybrid_data.json --out ./hybrid.pdf
"""

import json
import argparse
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.ticker import MaxNLocator, AutoMinorLocator
import matplotlib.transforms as transforms
from matplotlib.transforms import blended_transform_factory


def draw_hybrid_fig(data, out_pdf="./hybrid.pdf"):
    x_ratio       = data["x_ratio"]
    top_curve     = data["top_only"]
    curves_hybrid = {int(k): v for k, v in data["hybrid"].items()}
    zero_x        = {int(k): v for k, v in data["zero_crossings"].items()}
    params        = data["params"]
    top_n_list    = params["top_n_list"]
    error_metric  = params.get("error_metric", "signed_pp")
    sample_sizes  = data["sample_sizes"]

    fig, ax = plt.subplots(figsize=(3.7, 2.5), dpi=500)

    COLOR_TOP    = "#6b24bf"
    COLOR_RAND   = "#1F78B4"
    COLOR_STRAT  = "#33A02C"
    COLOR_BUCKET = "saddlebrown"

    ax.plot(x_ratio, top_curve, color=COLOR_TOP, lw=0.8, label="Top-only")

    marker_styles = ["o", "s", "D", "^", "v"]
    trans_x_ax   = blended_transform_factory(ax.transData, ax.transAxes)

    for idx_top, top_n in enumerate(top_n_list):
        marker   = marker_styles[idx_top % len(marker_styles)]
        curves_t = curves_hybrid.get(top_n, {})

        try:    start_idx = sample_sizes.index(int(top_n))
        except: start_idx = None

        rnd   = np.asarray(curves_t.get("random",     []), float)
        strat = np.asarray(curves_t.get("stratified", []), float)
        bkt   = np.asarray(curves_t.get("bucket",     []), float)

        if np.isfinite(rnd).any():
            ax.plot(x_ratio, rnd,   lw=0.8, color=COLOR_RAND,
                    label="Top N then Random (mean)" if idx_top == 0 else None)
        if np.isfinite(strat).any():
            ax.plot(x_ratio, strat, lw=0.8, color=COLOR_STRAT,
                    label="Top N then Stratified (mean)" if idx_top == 0 else None)
        if np.isfinite(bkt).any():
            ax.plot(x_ratio, bkt,   lw=0.8, color=COLOR_BUCKET,
                    label="Top N then Bucket (mean)" if idx_top == 0 else None)

        if start_idx is not None:
            anchor_y = next(
                (arr[start_idx] for arr in (rnd, strat, bkt)
                 if start_idx < len(arr) and np.isfinite(arr[start_idx])),
                float("nan"),
            )
            if np.isfinite(anchor_y):
                ax.scatter(x_ratio[start_idx], anchor_y,
                           color="black", marker=marker, s=5, zorder=10)
                ax.text(x_ratio[start_idx], anchor_y,
                        f"Top {top_n:,}", fontsize=4, color="black",
                        ha="left", va="bottom", zorder=11,
                        bbox=dict(facecolor="white", edgecolor="black",
                                  linewidth=0.6, boxstyle="round,pad=0.25", alpha=0.75))

    ax.axhline(0, color="gray", linestyle="--", lw=1.0, alpha=0.8)

    for top_n, zx in sorted(zero_x.items(), key=lambda kv: kv[1]):
        ax.axvline(zx, color="gray", linestyle="--", lw=0.8, alpha=0.7)
        ax.text(zx, 0.98, f"Top {top_n:,} → 0",
                rotation=90, va="top", ha="right", fontsize=4,
                transform=trans_x_ax,
                bbox=dict(facecolor="white", edgecolor="none", alpha=0.7, pad=1.5))

    ylabel = {
        "signed_pp":        "Deviation from baseline (%)",
        "relative_pct":     "Relative error from baseline (%)",
        "abs_relative_pct": "Absolute relative error (%)",
    }[error_metric]

    label_font_size = 4.5
    ax.set_xlabel("Sample size as a fraction of full website population",
                  fontsize=label_font_size)
    ax.set_ylabel(ylabel, fontsize=label_font_size, labelpad=1.0)
    ax.tick_params(axis="both", labelsize=5)
    ax.xaxis.set_major_locator(MaxNLocator(nbins=10))
    ax.xaxis.set_minor_locator(AutoMinorLocator(4))
    ax.set_xlim(0.0, 0.5)

    YMAX = 15.0; lin = 0.1
    ax.set_yscale("symlog", linthresh=lin, linscale=2.5, base=10)
    majloc     = mticker.SymmetricalLogLocator(base=10, linthresh=lin, subs=(1., 2., 5.))
    ticks_auto = majloc.tick_values(-YMAX, YMAX)
    ticks      = np.unique(np.concatenate([ticks_auto, np.linspace(-lin, lin, 13)]))
    ticks      = ticks[(ticks >= -YMAX) & (ticks <= YMAX)]
    ax.set_yticks(ticks)
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.2f"))
    ax.grid(True, which="major", linestyle="--", alpha=0.6, linewidth=0.4)
    ax.grid(True, which="minor", linestyle=":",  alpha=0.3, linewidth=0.4)
    for spine in ax.spines.values(): spine.set_linewidth(0.5)

    ax.legend(frameon=True, fontsize=4.5, loc="best")
    plt.tight_layout()

    if out_pdf:
        fig.savefig(out_pdf, bbox_inches="tight", pad_inches=0)
        print(f"Saved → {out_pdf}")
    return fig, ax


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Reproduce the hybrid sampling figure from pre-computed JSON data."
    )
    parser.add_argument("--data", default="./hybrid_data.json")
    parser.add_argument("--out",  default="./hybrid.pdf")
    args = parser.parse_args()

    print(f"Loading {args.data} …")
    with open(args.data) as f:
        data = json.load(f)

    prm = data.get("params", {})
    print(f"  N_POP={prm.get('N_POP')}  top_n_list={prm.get('top_n_list')}"
          f"  steps={len(data['x_ratio'])}  seed={prm.get('seed')}")

    fig, ax = draw_hybrid_fig(data, out_pdf=args.out)
    plt.show()
